<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_www.npru.ac.thNPRU</name>
   <tag></tag>
   <elementGuidId>f80226e7-9ef4-4b04-b2ea-2b0d4789e8fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.d-ib.fz-20.lh-26.td-hu.tc.va-bot.mxw-100p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5d812651-cc65-4a2d-9cc3-df4767428552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-ib fz-20 lh-26 td-hu tc va-bot mxw-100p</value>
      <webElementGuid>0b5ddd40-8fb2-4b22-a555-9a54cb95ac03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-matarget</name>
      <type>Main</type>
      <value>algo</value>
      <webElementGuid>f972ee74-5bbd-4c2d-a11e-fe1e388d3f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>6df702f1-c65f-4028-8483-87b2c4d6fbf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>referrerpolicy</name>
      <type>Main</type>
      <value>origin</value>
      <webElementGuid>a9c8dc12-8a2f-46de-baea-86222427e35c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.npru.ac.th/</value>
      <webElementGuid>e22ddd85-c30c-4141-98e4-aa34863d4b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-45c</name>
      <type>Main</type>
      <value>60f0b40a08fe44</value>
      <webElementGuid>4f396d2e-99ef-4de3-8e14-010d770c6e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>NPRU</value>
      <webElementGuid>b19f061e-4106-42c5-be00-1dac2183dda3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>www.npru.ac.thNPRU</value>
      <webElementGuid>a638286e-a8e7-48d2-9d60-d44d3613615e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;web&quot;)/ol[@class=&quot;reg  searchCenterMiddle&quot;]/li[@class=&quot;first&quot;]/div[@class=&quot;dd fst algo algo-sr relsrch richAlgo&quot;]/div[@class=&quot;compTitle options-toggle&quot;]/h3[@class=&quot;title&quot;]/a[@class=&quot;d-ib fz-20 lh-26 td-hu tc va-bot mxw-100p&quot;]</value>
      <webElementGuid>c1fcee3e-abb7-45f0-9421-f8646f519268</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='web']/ol/li/div/div/h3/a</value>
      <webElementGuid>b3edb2b2-61a4-43d5-a414-6f31eac38a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.npru.ac.th/')]</value>
      <webElementGuid>7086b001-be3a-4dde-bd44-03fecca29a65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a</value>
      <webElementGuid>f254375d-38df-43ae-a518-5d7ffabedc79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.npru.ac.th/' and (text() = 'www.npru.ac.thNPRU' or . = 'www.npru.ac.thNPRU')]</value>
      <webElementGuid>b1c362fe-20ed-4bec-b253-420912670df5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
